#!/bin/bash
echo "chmod 1 start"
chmod 555 /var/www/html/index.html
echo "chmod 1 done  chmod 2 start"
chmod 555 /var/www/html/index2.html
echo "chmod 2 done"
touch  /var/www/html/test.log
service httpd start

